routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('adm.index');
});

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/tes', function () {
    return view('tes');
});

Route::get('/login', function () {
    return redirect('/auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'AuthController@logout');

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'AuthController@logout');

Route::resource('category', 'categoryController')->middleware('auth');
Route::resource('notes', 'notesController')->middleware('auth');
Route::resource('spec', 'specController')->middleware('auth');
Route::resource('level', 'LevelController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');

app/Http/Controllers/notesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use  App\Models\notes;

class notesController extends Controller
{
    
    public function index()
    {
        $data=notes::all();
        return view('notes.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new notes();
		$data->judul = $request->judul;
        $data->note = $request->note;
		$data->save();
		return redirect()->route('notes.index')->with('alert-success', 'Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function aplikasi($id)
    {
       $aplikasi= aplikasi::where('server_id', $id)->get();
      
	   return view('notes.aplikasi',compact('aplikasi'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = notes::where('id', $id)->get();
		return view('notes.edit', compact('data'));
    }
    public function show($id)
    {
        $data = notes::where('id', $id)->get();
		return view('notes.show', compact('data'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = notes::where('id', $id)->first();
		$data->judul = $request->judul;
        $data->note = $request->note;
		$data->save();
		return redirect()->route('notes.index')->with('alert-success', 'Data berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = notes::where('id', $id)->first();
		$data->delete();
		return redirect()->route('notes.index')->with('alert-success', 'Data berhasi dihapus!');
    }
}

resources/views/notes/create.blade.php
@extends('layouts.adm') 
@section('content')
<!-- BEGIN CONTENT BODY -->
                <div class="page-content-wrapper">
                    <div class="content-wrapper container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="page-title">

                                    <h4 class="float-left">Create Notes</h4>

                                    <ol class="breadcrumb float-left float-md-right">
                                        <li class="breadcrumb-item"><a href="/notes"><i class="fa fa-arrow-left"></i></a></li>
                                    
                                    </ol>

                                </div>
                            </div>
                        </div><!-- end .page title-->

                            <div class="col-md-12">


                                <div class="col-md-12">
                                <div class="panel panel-card margin-b-30">
                                    
                                    <div class="panel-body  p-xl-3">
                                        <form class="form-horizontal" action="{{ route('notes.store') }}" method="post">
										{{ csrf_field() }}
										
										
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Judul</label>

                                                <div class="col-lg-10">
												<input type="text"  name="judul" placeholder="Judul" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Notes</label>

                                                <div class="col-lg-10">
                                                    <textarea class="ckeditor form-control" name="note"></textarea>
                                                </div>
                                            </div>
                                            
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>


                    <div class="clearfix"></div>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- /wrapper -->


        <!-- SCROLL TO TOP -->
        <a href="#" id="toTop"></a> 
	@endsection

<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>

resources/views/notes/edit.blade.php
@extends('layouts.adm') 
@section('content')
<!-- BEGIN CONTENT BODY -->
                <div class="page-content-wrapper">
                    <div class="content-wrapper container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="page-title">

                                    <h4 class="float-left">Edit Notes</h4>

                                    <ol class="breadcrumb float-left float-md-right">
                                        <li class="breadcrumb-item"><a href="/notes"><i class="fa fa-arrow-left"></i></a></li>

                                    </ol>

                                </div>
                            </div>
                        </div><!-- end .page title-->

                            <div class="col-md-12">


                                <div class="col-md-12">
                                <div class="panel panel-card margin-b-30">
                                    
                                    </div>
                                    <div class="panel-body  p-xl-3">
                                       
										@foreach($data as $datas)
										<form class="form-horizontal" action="{{ route('notes.update', $datas->id) }}" method="post">
										{{ csrf_field() }}
										{{ method_field('PUT') }}
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Judul</label>

                                                <div class="col-lg-10">
												<input type="text" name="judul" placeholder="Judul" value="{{ $datas->judul }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Notes</label>

                                                <div class="col-lg-10">
                                                <textarea class="ckeditor form-control"  name="note">{{ $datas->note }}"</textarea>

                                            </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>
										@endforeach
                                    </div>
                                </div>
                            </div>


                    <div class="clearfix"></div>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- /wrapper -->


        <!-- SCROLL TO TOP -->
        <a href="#" id="toTop"></a> 
	@endsection

    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>

resources/views/notes/index.blade.php
@extends('layouts.adm') 
@section('content')

<link href="{{ URL::asset('adm/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Notes <a href="{{ url('notes/create') }}" class="btn btn-sm btn-primary" >Create</a>
</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Notes</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>No</th>
            <th>Judul</th>
            <th>Notes</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>No</th>
            <th>Judul</th>
            <th>Notes</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
        @php
			$no = 1;
		@endphp
			@foreach($data as $items)
           <tr>
            <td>{{ $no++ }}</td>
            <td>{{ $items->judul }}</td>
            <td>  <a class="btn btn-sm btn-primary" type="submit"  href="{{ route('notes.show',$items->id) }}">Lihat</a></td>

			</td>
            <td>
            <form action="{{ route('notes.destroy', $items->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
              
                <a class="btn btn-sm btn-primary" type="submit" href="{{ route('notes.edit',$items->id) }}">Edit</a>
                <button style="color:white;" class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>

                 
                
                  
               
               

            </form>
            </td>
            </tr>
        @endforeach   
        </tbody>
      </table>
    </div>
  </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
  <div class="modal-footer">
    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
    <a class="btn btn-primary" href="{{ url('/logout') }}">Logout</a>
  </div>
</div>
</div>
</div>

@endsection

resources/views/notes/show.blade.php
@extends('layouts.adm') 
@section('content')


<!-- BEGIN CONTENT BODY -->
                <div class="page-content-wrapper">
                    <div class="content-wrapper container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="page-title">

                                    <h4 class="float-left">Notes Page</h4>

                                    <ol class="breadcrumb float-left float-md-right">
                                      <li class="breadcrumb-item"><a href="/notes"><i class="fa fa-arrow-left"></i></a></li>

                                    </ol>

                                </div>
                            </div>
                        </div><!-- end .page title-->

				
								<div class="col-md-12">
                                <div class="panel panel-card margin-b-30">
                                    <!-- Start .panel -->
                                   
                                       
                                        <div class="float-right">
                                            <div class="btn-group">
                                                
                                                <div class="dropdown-menu panel-dropdown" role="menu">
                                                    <a  class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>

                                                    <a class="dropdown-item" href="#">Separated link</a>
                                                </div>
                                            </div>
                                        </div>
                                 
                                    <div class="panel-body  p-xl-3">
                                        @foreach($data as $datas)
											 JUDUL : <b>{{$datas->judul}}</b>
											 <br>
											<div class="form-group row" style="background-color:white;height:600px;margin-top:10px">
											

                                                <div class="col-lg-12">
                                                	@php
									              echo $datas->note
									              @endphp	
                                                </div>
											</div>
											
											
										@endforeach
                                    </div>
                                </div>
				
				
				
				
				
				
				
				
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- /wrapper -->
		
		 

        <!-- SCROLL TO TOP -->
        <a href="#" id="toTop"></a> 
	@endsection