routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('adm.index');
});

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/tes', function () {
    return view('tes');
});

Route::get('/login', function () {
    return redirect('/auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'AuthController@logout');

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'AuthController@logout');

Route::resource('category', 'categoryController')->middleware('auth');
Route::resource('notes', 'notesController')->middleware('auth');
Route::resource('spec', 'specController')->middleware('auth');
Route::resource('level', 'LevelController')->middleware('auth');
Route::resource('user', 'UserController')->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'level_id', 'name', 'email', 'password', 'status_aktif',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function level(){
        return $this->belongsTo(Level::class,'level_id');
    }

    public function punyaLevel($level){
        // dd($this->Level);
        if($this->Level->level==$level){
            return true;
        }
        return false;
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use  App\Models\User;
use  App\Models\Level;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$data = User::whereNotIn('level_id', [1, 5])->get();
		$data = User::all();
        return view('user.index', compact('data'));
    }

    public function create()
    {
        $data = Level::all();
        return view('user.add', compact('data'));
    }


	public function store(Request $req)
    {
        
            $simpan=new User;
		    $simpan->level_id = $req->input('level_id');
            $simpan->name = $req -> input('name');
            $simpan->email = $req ->input('email');
            $simpan->password = hash::make($req->input('password'));
		    $simpan->status_aktif = $req -> input('status_aktif');
            $simpan->save();
		return redirect()->route('user.index')->with('alert-success', 'Berhasil Menambahkan Data!');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = User::findOrFail($id);
        $level = Level::whereNotIn('id', [1, 5])->get();
        return view('user.edit', compact('data', 'level'));
    }

    public function update(Request $request, $id)
    {
        $data = User::findOrFail($id);
        $input = $request->all();
        $data->update($input);
        return redirect()->route('user.index')->with('alert-success', 'Berhasil Update Data!');
    }

    public function destroy($id)
    {
        $data = User::findOrFail($id);
        $data->delete();
        return redirect()->route('user.index')->with('alert-success', 'Berhasil Hapus Data!');
    }
}

resources/views/user/add.blade.php
@extends('layouts.adm') 
@section('content')
<!-- BEGIN CONTENT BODY -->
                <div class="page-content-wrapper">
                    <div class="content-wrapper container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="page-title">

                                    <h4 class="float-left">Create User</h4>

                                    <ol class="breadcrumb float-left float-md-right">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);"><i class="fa fa-home"></i></a></li>
                                        <li class="breadcrumb-item">User</li>
                                    </ol>

                                </div>
                            </div>
                        </div><!-- end .page title-->

                            <div class="col-md-12">


                                <div class="col-md-6">
                                <div class="panel panel-card margin-b-30">
                                    <!-- Start .panel -->
                                    <div class="card-header">
                                        Create User
                                        <div class="float-right">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-info btn-rounded btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Action <span class="caret"></span></button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel-body  p-xl-3">
                                        <form class="form-horizontal" action="{{ route('user.store') }}" method="post">
										{{ csrf_field() }}
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Level</label>

                                                <div class="col-lg-10">
                                                <select name="level_id" id="level_id" class="form-control{{ $errors->has('level_id') ? ' is-invalid' : '' }}">
                                                    <option>Select Level</option>

                                                    @foreach($data as $level)
                                                      <option value="{{ $level->id }}"> {{ $level->name }}</option>
                                                    @endforeach
                                                  </select>

                                                  @if ($errors->has('level_id'))
                                                      <span class="invalid-feedback" role="alert">
                                                          <strong>{{ $errors->first('level_id') }}</strong>
                                                      </span>
                                                  @endif
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Nama</label>

                                                <div class="col-lg-10">
												<input type="text" name="name" placeholder="Nama" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Email</label>

                                                <div class="col-lg-10">
                                                <input type="email" name="email" placeholder="Email" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Password</label>

                                                <div class="col-lg-10">
                                                <input type="password"  placeholder="Password" name="password" class="form-control" required> 
                                                </div>
                                            </div>

                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Status</label>

                                                <div class="col-lg-10">
												<select name="status_aktif" class="form-control select">
													<option value="1">Aktif</option>
													<option value="0">Tidak Aktif</option>
												</select>
                                            </div>
											</div>
                                            <div class="form-group row">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>


                    <div class="clearfix"></div>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- /wrapper -->


        <!-- SCROLL TO TOP -->
        <a href="#" id="toTop"></a> 
@endsection

resources/views/user/edit.blade.php
@extends('layouts.adm') 
@section('content')
<!-- BEGIN CONTENT BODY -->
                <div class="page-content-wrapper">
                    <div class="content-wrapper container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="page-title">

                                    <h4 class="float-left">Edit User</h4>

                                    <ol class="breadcrumb float-left float-md-right">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);"><i class="fa fa-home"></i></a></li>
                                        <li class="breadcrumb-item">User</li>
                                    </ol>

                                </div>
                            </div>
                        </div><!-- end .page title-->

                            <div class="col-md-12">


                                <div class="col-md-6">
                                <div class="panel panel-card margin-b-30">
                                    <!-- Start .panel -->
                                    <div class="card-header">
                                        Edit User
                                        <div class="float-right">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-info btn-rounded btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Action <span class="caret"></span></button>
                                                <div class="dropdown-menu panel-dropdown" role="menu">
                                                    <a  class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>

                                                    <a class="dropdown-item" href="#">Separated link</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel-body  p-xl-3">
                                        <form class="form-horizontal" action="{{ route('user.update', $data->id) }}" method="post">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="PATCH">
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Level</label>

                                                <div class="col-lg-10">
                                                <select name="level_id" id="level_id" class="form-control{{ $errors->has('level_id') ? ' is-invalid' : '' }}">
                                                    <option>Select Level</option>

                                                    @foreach($level as $level)
                                                      <option value="{{ $level->id }}"> {{ $level->level }}</option>
                                                    @endforeach
                                                  </select>

                                                  @if ($errors->has('level_id'))
                                                      <span class="invalid-feedback" role="alert">
                                                          <strong>{{ $errors->first('level_id') }}</strong>
                                                      </span>
                                                  @endif
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Nama</label>

                                                <div class="col-lg-10">
                                                <input type="text" name="name" placeholder="Nama" value="{{ $data->name }}" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Email</label>

                                                <div class="col-lg-10">
                                                <input type="email" name="email" value="{{ $data->email }}" placeholder="Email" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Password</label>

                                                <div class="col-lg-10">
                                                <input type="password" name="password" class="form-control" required> 
                                                </div>
                                            </div>
											
											
											 <div class="form-group row"><label class="col-lg-2 form-control-label">NIP</label>

                                                <div class="col-lg-10">
                                                <input type="text" name="nip" placeholder="NIP" value="{{ $data->nip }}" class="form-control" required> 
                                                </div>
                                            </div>
											
											 <div class="form-group row"><label class="col-lg-2 form-control-label">Jabatan</label>

                                                <div class="col-lg-10">
                                                <input type="text" name="jabatan" placeholder="Jabatan" value="{{ $data->jabatan }}" class="form-control" required> 
                                                </div>
                                            </div>
											
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">NIK</label>

                                                <div class="col-lg-10">
                                                <input type="text" name="nik" placeholder="NIK" value="{{ $data->nik }}" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">No HP</label>

                                                <div class="col-lg-10">
                                                <input type="text" name="no_hp" placeholder="No HP" value="{{ $data->no_hp }}" class="form-control" required> 
                                                </div>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Jenis Kelamin</label>

                                                <div class="col-lg-10">
                                                <select name="jenis_kelamin" class="form-control select">
                                                    <option value="1">Laki-laki</option>
                                                    <option value="2">Perempuan</option>
                                                </select>
                                            </div>
                                            <div class="form-group row"><label class="col-lg-2 form-control-label">Status</label>

                                                <div class="col-lg-10">
                                                <select name="status_aktif" class="form-control select">
                                                    <option value="1">Aktif</option>
                                                    <option value="0">Tidak Aktif</option>
                                                </select>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>


                    <div class="clearfix"></div>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTAINER -->
        </div>
        <!-- /wrapper -->


        <!-- SCROLL TO TOP -->
        <a href="#" id="toTop"></a> 
@endsection

resources/views/user/index.blade.php
@extends('layouts.adm')
@section('content')


<link href="{{ URL::asset('adm/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">User {{$kategori->kategori ?? ''}}</h1>
<a href="{{ url('user/create') }}" class="btn btn-sm btn-primary" >Create</a>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Aset {{$kategori->kategori ?? ''}}</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Email</th>
            <th>Level</th>
            <th>Status Aktif</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Email</th>
			      <th>Level</th>
            <th>Status Aktif</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
            @php
            $no = 1;
            @endphp
            @foreach($data as $items)
            <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $items->name }}</td>
                <td>{{ $items->email }}</td>
                <td>{{$items->level->name}}</td>
                <td>
                    @if ($items->status_aktif == 1)
                        <a class="tag label-info">Aktif</a>
                    @elseif ($items->status_aktif == 0)
                        <a class="tag label-danger">Tidak Aktif</a>
                    @else
                        Tidak
                    @endif
                </td>
                <td>
				
                <form action="{{ route('user.destroy', $items->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <!--<a href="{{ route('user.show',$items->id) }}">Lihat</a>
                    <a class="btn btn-sm btn-success" type="submit" href="{{ route('user.edit',$items->id) }}">Edit</a>-->
                    @if ($items->status_aktif == 0)
                    <a style="color:white;" class="btn btn-sm btn-success" type="submit" href="{{ route('user.update',$items->id) }}" onclick="return confirm('Yakin ingin mengaktifkan akun ini?')">Aktifkan</a>
                    @endif
                    <button style="color:white;" class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                </form>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
  <div class="modal-footer">
    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
    <a class="btn btn-primary" href="{{ url('/logout') }}">Logout</a>
  </div>
</div>
</div>
</div>

@endsection